// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHeWMOTyDZjoxffkt1lPnoI6gjGUt_Ts',
    appId: '1:422849154400:web:71a6ab3aca70cceb406205',
    messagingSenderId: '422849154400',
    projectId: 'blogrecipe-34851',
    authDomain: 'blogrecipe-34851.firebaseapp.com',
    storageBucket: 'blogrecipe-34851.firebasestorage.app',
    measurementId: 'G-LDG1JQ21NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7h-0hH2VVdaONqLH4omon5KEPJgN0P4',
    appId: '1:422849154400:android:fb2d3caf4af7318c406205',
    messagingSenderId: '422849154400',
    projectId: 'blogrecipe-34851',
    storageBucket: 'blogrecipe-34851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE1B-nEpKt76uFnTxr4UfvmeflZxgEwNY',
    appId: '1:422849154400:ios:6cb7be1ea714a158406205',
    messagingSenderId: '422849154400',
    projectId: 'blogrecipe-34851',
    storageBucket: 'blogrecipe-34851.firebasestorage.app',
    iosBundleId: 'com.example.blogfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE1B-nEpKt76uFnTxr4UfvmeflZxgEwNY',
    appId: '1:422849154400:ios:6cb7be1ea714a158406205',
    messagingSenderId: '422849154400',
    projectId: 'blogrecipe-34851',
    storageBucket: 'blogrecipe-34851.firebasestorage.app',
    iosBundleId: 'com.example.blogfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbHeWMOTyDZjoxffkt1lPnoI6gjGUt_Ts',
    appId: '1:422849154400:web:a30970dad879d151406205',
    messagingSenderId: '422849154400',
    projectId: 'blogrecipe-34851',
    authDomain: 'blogrecipe-34851.firebaseapp.com',
    storageBucket: 'blogrecipe-34851.firebasestorage.app',
    measurementId: 'G-E784WQP8RG',
  );
}
